# from micropython import const
# pumps
PUMP_1_PIN_NUM = 33
PUMP_2_PIN_NUM = 25
PUMP_3_PIN_NUM = 26
PUMP_4_PIN_NUM = 27

# linear actuator
RAISE_LINEAR_ACTUATOR_PIN_NUM = 14
LOWER_LINEAR_ACTUATOR_PIN_NUM = 12
TOP_LIMIT_SWITCH_PIN_NUM = 34 #TODO RENAME
BOTTOM_LIMIT_SWITCH_PIN_NUM = 39

# encoder push button
MENU_SCROLL_A_PIN_NUM = 32
MENU_SCROLL_B_PIN_NUM = 35
MENU_SELECT_PIN_NUM   = 4

# OLED Screen
MOSI_PIN_NUM = 23
MISO_PIN_NUM = 19
SCK_PIN_NUM  = 18
OLED_CS_PIN_NUM = 5
OLED_RESET_PIN_NUM = 16
OLED_DC_PIN_NUM = 17

# I2C
SCL_PIN_NUM = 22
SDA_PIN_NUM = 21

# HX711
HX711_SCK_PIN_NUM = 22
HX711_SDA_PIN_NUM = 21

# Neopixel
NEOPIXEL_PIN_NUM = 15